version: "3.9"
services:
  nextjs:
    build: ./
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./styles:/app/styles
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./globals.d.ts:/app/globals.d.ts
      - ./.env.development:/app/.env.development
      - ./jest.config.ts:/app/jest.config.ts
      - ./babel.config.js:/app/babel.config.js